server:
  port: 9001
spring:
  application:
    name: admin

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/jnu?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true
      username: root
      password: 112233
      driverClassName: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      filters: stat
      maxActive: 20
      initialSize: 5
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
  redis:
    database: 0
    host: 127.0.0.1
    password: ''
    port: 6379
    timeout: 3000

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

feign:
  client:
    config:
      default:
        connect-timeout: 10000
        read-timeout: 10000

mybatis-plus:
  #指定mapper路径
  mapperLocations: classpath*:com/jnu/example/**/mapper/**/*.xml
  global-config:
    db-config:
      #主键类型  "数据库ID自增", "用户输入ID","全局唯一ID (数字类型唯一ID)", "全局唯一ID UUID";
      id-type: ASSIGN_UUID
      #字段策略 0:"忽略判断",1:"非NULL判断",2:"非空判断"
      field-strategy: 1
      #驼峰下划线转换
      db-column-underline: false
  configuration:
    default-enum-type-handler: com.jnu.example.core.handler.MybatisEnumTypeHandler


upload:
  rootPath: ./uploads


#分布式事务配置
seata:
  enabled: false
  application-id: ${spring.application.name} # Seata 应用名称，默认使用 ${spring.application.name}
  tx-service-group: ngsp-s-auth-group   #事务分组配置
  enable-auto-data-source-proxy: true
  service:
    vgroupMapping:
      ngsp-s-auth-group: ngsp-s-auth-cluster
    grouplist:
      default: 10.64.200.64:8091
    enable-degrade: false
    disable-global-transaction: false
  config:
    type: nacos
    nacos:
      namespace:
      group: SEATA_GROUP    #nacos控制台配置分组
      userName: "nacos"
      password: "nacos"
      server-addr: ${spring.cloud.nacos.discovery.server-addr}
  registry:
    type: nacos
    nacos:
      application: seata-server    #指定seata服务器地址
      server-addr: ${spring.cloud.nacos.discovery.server-addr}
      namespace:
      userName: "nacos"
      password: "nacos"

logging:
  level:
    com.jnu.example.db.admin.mapper: debug